index:
    path: /
    defaults: { _controller: 'App\Controller\StartController::index' }

admin:
    path: /admin
    defaults: { _controller: 'App\Controller\BlogPostController::index' }

admin_create:
    path: /admin/create
    defaults: { _controller: 'App\Controller\BlogPostController::create' }
