index:
    path: /
    defaults: { _controller: 'App\Controller\Frontend\StartController::index' }

admin:
    path: /admin
    defaults: { _controller: 'App\Controller\Backend\AdminController::index' }

admin_create:
    path: /admin/create
    defaults: { _controller: 'App\Controller\Backend\BlogPostController::create' }
